### ISSUE TITLE
Add Install command of package "net-tools" 

### ISSUE THREAD

**Issue by francisafu** [abiyo/Strongswan-install#1]
Hi abiyo,

I am really appreciate your work. The script is GREAT!

However, When I test it, I found that an error may occur when try to access the "route" command on some purely install Ubuntu 20.04, due to the lack of net-tools. Thus will made everything goes wrong from line 103, since we cannot get the correct name of ethernet card.

I suggest to add a line before start the install procudure: apt install net-tools

It will fix this situation perfectly.

Francis

**Comment by abiyo** [comment]
> Hi abiyo,
> 
> I am really appreciate your work. The script is GREAT!
> 
> However, When I test it, I found that an error may occur when try to access the "route" command on some purely install Ubuntu 20.04, due to the lack of net-tools. Thus will made everything goes wrong from line 103, since we cannot get the correct name of ethernet card.
> 
> I suggest to add a line before start the install procudure: apt install net-tools
> 
> It will fix this situation perfectly.
> 
> Francis

Hi Francis,

You're right.
I have added it. Thank you for test and your notice.
